### ISSUE TITLE
老铁，你这代码是最新的不，为啥猫眼的数据获取不到啊

### ISSUE THREAD

**Issue by JUSTLEARNING-96** [fengxin-zhxx/douban-master#1]

**Comment by JUSTLEARNING-96** [comment]
![Uploading 图片.png…]()

**Comment by JUSTLEARNING-96** [comment]
作者，江湖救急啊

**Comment by fengxin-zhxx** [comment]
> 作者，江湖救急啊

抱歉，当时是能跑的，不清楚豆瓣是不是搞了反爬虫

**Comment by JUSTLEARNING-96** [comment]
> > 作者，江湖救急啊
> 
> 抱歉，当时是能跑的，不清楚豆瓣是不是搞了反爬虫

豆瓣的我用多IP代理爬了，但是猫眼的获取不到

**Comment by fengxin-zhxx** [comment]
> > > 作者，江湖救急啊
> > 
> > 抱歉，当时是能跑的，不清楚豆瓣是不是搞了反爬虫
> 
> 豆瓣的我用多IP代理爬了，但是猫眼的获取不到

估计是更新过了，我很久不做这类东西啦

**Comment by JUSTLEARNING-96** [comment]
def get_data_maoyan(html : str):
    if local_test:
        with open("./html/maoyan.html", 'r', encoding='utf-8') as f:
            html = f.read()
    else:
        html = get_html(url)  #请问一下这里为啥不是用猫眼网的地址  要用豆瓣的地址啊
        with open("./html/maoyan.html", 'w+', encoding='utf-8') as f:
            f.write(html.encode('utf-8').decode('utf-8'))

**Comment by JUSTLEARNING-96** [comment]
作者  如果你还记得的话

**Comment by fengxin-zhxx** [comment]
> def get_data_maoyan(html : str): if local_test: with open("./html/maoyan.html", 'r', encoding='utf-8') as f: html = f.read() else: html = get_html(url) #请问一下这里为啥不是用猫眼网的地址 要用豆瓣的地址啊 with open("./html/maoyan.html", 'w+', encoding='utf-8') as f: f.write(html.encode('utf-8').decode('utf-8'))

https://github.com/fengxin-zhxx/douban-master/blob/5dcc009467236e879eed9afd4cdb03be7d8048e4/src/main.py#L176
传入的是猫眼的网址
